const USER_EMAIL_CONFIRMATION_CODE_TTL = 15 * 60; // 15 minutes
const USER_SESSION_TTL = 15 * 60 * 60; // 15 days
const CONFIRM_CODE_REDIS_TAG = 'email_confirmation_code';
const MAX_DEVICES = 3;

export { USER_SESSION_TTL, USER_EMAIL_CONFIRMATION_CODE_TTL, CONFIRM_CODE_REDIS_TAG, MAX_DEVICES };
